# Pydantic Models for MongoDB Documents
# MongoDB doesn't need SQLAlchemy - it works directly with JSON/dictionaries
# We only need Pydantic for validation

from pydantic import BaseModel, Field, EmailStr
from typing import Optional
from datetime import datetime
from bson import ObjectId


# Custom type for MongoDB's ObjectId
# MongoDB uses ObjectId for _id field, but Pydantic doesn't know about it
class PyObjectId(ObjectId):
    """
    Custom type to handle MongoDB's ObjectId in Pydantic models.

    MongoDB's _id field uses ObjectId (like "507f1f77bcf86cd799439011")
    Pydantic v2 compatible validator.
    """

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.union_schema([
            core_schema.is_instance_schema(ObjectId),
            core_schema.chain_schema([
                core_schema.str_schema(),
                core_schema.no_info_plain_validator_function(cls.validate),
            ])
        ],
        serialization=core_schema.plain_serializer_function_ser_schema(
            lambda x: str(x)
        ))

    @classmethod
    def validate(cls, v):
        if isinstance(v, ObjectId):
            return v
        if isinstance(v, str):
            if ObjectId.is_valid(v):
                return ObjectId(v)
        raise ValueError("Invalid ObjectId")

    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema, handler):
        return {"type": "string"}


# ============================================================================
# USER MODELS
# ============================================================================

class UserBase(BaseModel):
    """
    Base user model with common fields.
    Used as parent for other user models.
    """
    username: str = Field(..., min_length=3, max_length=50)
    email: EmailStr  # Validates email format automatically


class UserCreate(UserBase):
    """
    Model for creating a new user.
    Used in POST /users endpoint.

    Only includes fields the client should provide.
    """
    pass  # Inherits username and email from UserBase


class UserUpdate(BaseModel):
    """
    Model for updating a user.
    Used in PUT /users/{id} endpoint.

    All fields optional (partial update).
    """
    username: Optional[str] = Field(None, min_length=3, max_length=50)
    email: Optional[EmailStr] = None


class UserInDB(UserBase):
    """
    Model representing user document in MongoDB.
    Includes database-generated fields.
    """
    id: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        # Allow population by field name (for MongoDB's _id)
        populate_by_name = True
        # Convert ObjectId to string when serializing to JSON
        json_encoders = {ObjectId: str}
        # Example of what this model looks like
        json_schema_extra = {
            "example": {
                "_id": "507f1f77bcf86cd799439011",
                "username": "alice",
                "email": "alice@example.com",
                "created_at": "2025-11-13T12:00:00"
            }
        }


class User(UserInDB):
    """
    Model for API responses.
    Used in GET /users endpoints.

    Same as UserInDB but used for clarity in API.
    """
    pass


# ============================================================================
# CONVERSATION MODELS
# ============================================================================

class ConversationBase(BaseModel):
    """
    Base conversation model with common fields.
    """
    user_id: str = Field(..., description="Username of the user")
    message: str = Field(..., min_length=1, max_length=1000)
    bot_reply: str = Field(..., min_length=1)


class ConversationCreate(ConversationBase):
    """
    Model for creating a new conversation.
    Used in POST /conversations endpoint.

    Client provides user_id and message.
    Bot_reply can be generated by the bot.
    """
    bot_reply: str = Field(default="", description="Generated by bot if empty")


class ConversationUpdate(BaseModel):
    """
    Model for updating a conversation.
    Used in PUT /conversations/{id} endpoint.

    All fields optional (partial update).
    """
    message: Optional[str] = Field(None, min_length=1, max_length=1000)
    bot_reply: Optional[str] = Field(None, min_length=1)


class ConversationInDB(ConversationBase):
    """
    Model representing conversation document in MongoDB.
    Includes database-generated fields.
    """
    id: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        populate_by_name = True
        json_encoders = {ObjectId: str}
        json_schema_extra = {
            "example": {
                "_id": "507f1f77bcf86cd799439012",
                "user_id": "alice",
                "message": "Hello chatbot!",
                "bot_reply": "Hi there! How can I help?",
                "created_at": "2025-11-13T12:00:00"
            }
        }


class Conversation(ConversationInDB):
    """
    Model for API responses.
    Used in GET /conversations endpoints.
    """
    pass


# ============================================================================
# CHAT REQUEST/RESPONSE MODELS (For chatbot endpoint)
# ============================================================================

class ChatRequest(BaseModel):
    """
    Model for chatbot request.
    Used in POST /chat endpoint.
    """
    user_id: str
    user_message: str = Field(..., min_length=1, max_length=1000)

    class Config:
        json_schema_extra = {
            "example": {
                "user_id": "alice",
                "user_message": "Hello! How are you?"
            }
        }


class ChatResponse(BaseModel):
    """
    Model for chatbot response.
    Returns bot reply and conversation metadata.
    """
    bot_reply: str
    user_message: str
    conversation_id: str
    timestamp: str

    class Config:
        json_schema_extra = {
            "example": {
                "bot_reply": "I'm doing great! How can I help you?",
                "user_message": "Hello! How are you?",
                "conversation_id": "507f1f77bcf86cd799439013",
                "timestamp": "2025-11-13 12:00:00"
            }
        }
